name: geo_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - gdal=3.11.3
  - geopandas=1.1.1
  - numpy
  - pandas
  - pygmt
  - gmt   
  - pip
  - pip:
      - -r requirements.txt
      - MinsarPlotData
      - git+https://github.com/username/minsar.git
      - mintpy
      - pytest
