name: geo_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pygmt
  - xarray
  - pandas
  - cartopy
  - scipy
  - scikit-learn
  - simplekml
  - geopandas
  - mintpy
  - pip
  - pip:
      - MinsarPlotData
      - pytest