version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Miniconda and create environment
          command: |
            curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            source $HOME/miniconda/bin/activate
            conda env create -f environment.yml
      - run:
          name: Activate environment and run tests
          command: |
            source $HOME/miniconda/bin/activate plot_data
            pip install -r requirements.txt
            pip install MinsarPlotData 
            pytest

workflows:
  sample:
    jobs:
      - build-and-test
